# Generated by Django 5.0.6 on 2024-06-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_value', models.CharField(choices=[('liters', 'Liters'), ('pieces', 'Pieces'), ('kilos', 'Kilos'), ('grams', 'Grams'), ('packs', 'Packs')], default='pieces', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('needed_ings_amount', models.PositiveIntegerField(default=0)),
                ('recipe', models.ManyToManyField(to='food.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodrecipes')),
            ],
        ),
    ]
