# Generated by Django 5.0.6 on 2024-06-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientsAmount',
        ),
    ]
